version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/blockchain.js"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/blockchain.rs"
    schedule:
      interval: "weekly"
